import Head from 'next/head';
import { Homepage } from './Homepage';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Sam Adjei | Freelance Jamstack Developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Homepage />
			</main>
		</div>
	);
}
